"""empty message

Revision ID: 748250b3e96d
Revises: 3ee95082707d
Create Date: 2023-05-02 12:48:18.481678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748250b3e96d'
down_revision = '3ee95082707d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pro_video',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('videoProduct_id', sa.String(length=32), nullable=True),
    sa.Column('video_path', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['videoProduct_id'], ['products.product_id'], name=op.f('fk_pro_video_videoProduct_id_products')),
    sa.PrimaryKeyConstraint('video_id', name=op.f('pk_pro_video'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pro_video')
    # ### end Alembic commands ###
